### ISSUE TITLE
Allow DPPP to apply losoto solutions of type phase_offset

### ISSUE THREAD

**Issue by adrabent** [lofar-astron/DP3#101]
In `prefactor` we encountered the issue that DPPP can not be enforced to apply the phase_offset solutions from a clock-TEC separation operation in `losoto`:

In the h5parm the table is stored as such:
Solution table 'phase_offset000' (type: phase_offset): 60 ants
    Flagged data: 0.000%
    History: 2018-12-11 12:06:53: CREATE (by CLOCKTECFIT operation)

A minimum example of a `DPPP` parset:
`msin.datacolumn=DATA`
`msout=.`
`msout.datacolumn=CORRECTED_DATA_ion_phase_offset`
`msout.storagemanager=dysco`
`steps = [apply_offset]`
`apply_offset.type = applycal`
`apply_offset.correction = phase_offset000`
`apply_offset.parmdb = ../prefactor_calibrator/workdir/Pre-Facet-Calibrator/instrument.h5imp_cal_ion`

raises the following error:
`std exception detected: Unknown correction type: phase_offset`

I can not enforce `DPPP` using one of the other correction types (gain, commonscalarphase) with

`apply_offset.correction = commonscalarphase`
`apply_offset.soltab = phase_offset000`

In that situation `DPPP` simply ignores the `soltab` argument.

**Comment by revoltek** [comment]
I think the solution is to save that table as phase and not phase_offset in the h5parm. @maaijke can confirm if this is the right thing to do

**Comment by rvweeren** [comment]
Agree with @revoltek (just save it in the proper format in losoto, no need to create a new type, we already have a phase type...)

**Comment by maaijke** [comment]
Yes saving as phase makes sense

**Comment by aroffringa** [comment]
Would this be fixed by solving #16 ?

**Comment by revoltek** [comment]
@aroffringa I think no as the soltype of that soltab is set as phase_offset which is a non-standard soltype. The CT separation operation in losoto needs to be updated to save it as phase.

**Comment by revoltek** [comment]
@aroffringa I think this should be closed as it's a losoto issue
