### ISSUE TITLE
BucketCache: bucket <number> exceeds nr of buckets

### ISSUE THREAD

**Issue by tikk3r** [lofar-astron/DP3#103]
Not exactly sure what this is, but I figured this might be the best place to ask. When trying to run an 8 hour pointing on 3C 48 (full international array) through the calibrator parset of prefactor version 3.0, I encounter the following error during the `ndppp_prep_cal` step:

    std exception detected: BucketCache::getBucket: bucket 40 exceeds nr of buckets

For one it's `bucket 40` and for the other it's `bucket 0. The other subbands seem to work fine.

It only happens on two subbands only, so I'm trying to rerun it now, excluding these two subbands. I was wondering what this could be. Am I asking too much of the software trying this?

Here is what DPPP outputs before this error:

```
Finished preparing output MS
MSReader
  input MS:       /disks/paradata/sweijen/long_baseline_calibrator_models/3C48/observations/L691728/data/L691728_SB210_uv.MS
  baseline:       *
  band            0
  startchan:      0  (0) 
  nchan:          16  (0)
  ncorrelations:  4
  nbaselines:     2701   
  ntimes:         28760
  time interval:  1.00139
  DATA column:    DATA   
  WEIGHT column:  WEIGHT_SPECTRUM
  autoweight:     false  
PreFlagger flagbaseline.
  mode:           set
PreFlagger flagelev.
  mode:           set
   azimuth:       []
   elevation:     [0deg..20deg]
PreFlagger flagamp.
  mode:           set
   amplmin:       [1e-30,1e-30,1e-30,1e-30]
   amplmax:       [1e+30,1e+30,1e+30,1e+30]
Interpolate interp.
  windowsize:     15     
Averager avg.
  freqstep:       4 (set by freqresolution: 48820 Hz)
  timestep:       4 (set by timeresolution: 4)
  minpoints:      1      
  minperc:        0
MSWriter msout. 
  output MS:      /net/lofar6/data1/sweijen/3C48_8hr/prefactor/Pre-Facet-Calibrator/L691728_SB210_uv.ndppp_prep_cal
  nchan:          4
  ncorrelations:  4
  nbaselines:     2701   
  ntimes:         7190
  time interval:  4.00556
  DATA column:    DATA   
  WEIGHT column:  WEIGHT_SPECTRUM
  Compressed:     yes    
  Data bitrate:   0
  Weight bitrate: 12
  Dysco mode:     AF TruncatedGaussian(2.5)

Processing 28760 time slots ...

0%

std exception detected: BucketCache::getBucket: bucket 40 exceeds nr of buckets
```

**Comment by aroffringa** [comment]
This indicates that your measurement set is broken, for example because of a transfer failure. The exception is generated by the Casacore library, so DP3 cannot do much about it.

**Comment by tikk3r** [comment]
Ah I see. Thanks for the explanation.
