### ISSUE TITLE
undefined symbol: PyProperty_Type

### ISSUE THREAD

**Issue by revoltek** [lofar-astron/DP3#114]
Hi,

compiling the latest DP3 on ubuntu everything works fine, but I end up with:
DPPP: symbol lookup error: /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.65.1: undefined symbol: PyProperty_Type

when I try to run the program. Do you know what can cause this problem?

thanks

**Comment by aroffringa** [comment]
Don't know, but likely your lib setup. I'm not a sysadmin, so you'll have to find such help somewhere else...
