### ISSUE TITLE
numthread=0 hangs

### ISSUE THREAD

**Issue by revoltek** [lofar-astron/DP3#115]
With "numthreads = 0" DPPP doesn't stat, it stays hang at 0%. Correct behavior should be to use all CPUs.

**Comment by aroffringa** [comment]
The documentation doesn't say that numthreads=0 means all threads. Just leave numthreads out to do that...

**Comment by revoltek** [comment]
I see, that was just the old behavior then

**Comment by aroffringa** [comment]
That might be indeed. Anyway, I don't think this needs fixing so I'm closing this.
