### ISSUE TITLE
Predict only unflagged vis?

### ISSUE THREAD

**Issue by revoltek** [lofar-astron/DP3#120]
I was wondering if a possible large speed-up in the predict could come from predicting only unflagged visibilities. Maybe an easier initial implementation could be to skip completely flagged timestamps/channels/antenna.

**Comment by aroffringa** [comment]
Sometimes it is necessary to predict flagged values, so in any case it would be optional.

I'm not sure it's worth to pursue this. In normal cases the nr of flagged values should be much less than 50%, so the benefit would be less than a factor of two. Combined with the increased logic that would be required in prediction, that increases the complexity, I'd say it's better to look for speed up elsewhere...

**Comment by tammojan** [comment]
I vote as well for a 'wontfix' here. It is already possible to skip predicting on totally flagged channels and antennas by using a filter step.
