### ISSUE TITLE
std exception detected: Resource temporarily unavailable

### ISSUE THREAD

**Issue by revoltek** [lofar-astron/DP3#124]
Since a couple of weeks I (sometimes) get this error when I do a predict. Can you give me any hint on where to look at?

MSReader
  input MS:       /localwork/fdg/LBAsurvey/c07-o05/3c380/3c380_t1204_SB249.MS
  band            0
  startchan:      0  (0)
  nchan:          4  (0)
  ncorrelations:  4
  nbaselines:     666
  ntimes:         899
  time interval:  4.00556
  DATA column:    DATA
  WEIGHT column:  WEIGHT_SPECTRUM
  autoweight:     false
Predict pre.
  sourcedb:           3c380_t1204_SB249.MS/calib-simple.skydb
   number of patches: 1
   number of sources: 1
   all unpolarized:   true
  apply beam:         false
  operation:          replace
  threads:            1
MSUpdater msout.
  MS:             /localwork/fdg/LBAsurvey/c07-o05/3c380/3c380_t1204_SB249.MS
  datacolumn:     MODEL_DATA  (has been added to the MS)
  weightcolumn    WEIGHT_SPECTRUM
  writing:        data
  Compressed:     no

  flush:          0

Processing 899 time slots ...

0%....10....20....30....40.
std exception detected: Resource temporarily unavailable

**Comment by aroffringa** [comment]
This could be caused by exceeding the number of threads that your system supports.

**Comment by revoltek** [comment]
I asked to the sysadm but they said there's no limit to the max number of threads. It's also curious that it happens only, say, 50% of the runs.

**Comment by aroffringa** [comment]
Can you run a backtrace from the exception?

That's done like this:

    gdb -arg DPPP yourparameters...
    catch throw
    run

And then if it crashes, type 'bt'.
