### ISSUE TITLE
ddecal segmentation fault, too many open threads

### ISSUE THREAD

**Issue by rvweeren** [lofar-astron/DP3#126]
We are having in trouble getting ddecal to work, getting "OpenBLAS : Program will terminate because you tried to start too many threads." errors/segfaults, see all the way below.

Doing 
```
export OMP_NUM_THREADS=1
export OMP_MAX_THREADS=1
export OPENBLAS_NUM_THREADS=1
export OPENBLAS_MAX_THREADS=1
```

Does not fix the issue. Running with `DPPP numthreads=1` works, but then ddecal is slow and uses only one cpu. We (Frits) tried to recompile OpenBLAS with `USE_OPENMP=1` but that does not make a difference, we keep getting the same errors. (the error seems to be ddecal specific, I've not experienced other issues)

```
Singularity lofarddf.simg:/data2/rvweeren/DR2selfcal/testsing> DPPP msin=test.ms msin.datacolumn=DATA msout=. msin.modelcolumn=DATA steps=[ddecal] ddecal.type=ddecal ddecal.maxiter=1 ddecal.usemodelcolumn=True ddecal.nchan=1 ddecal.mode=complexgain ddecal.h5parm=templatejones.h5 ddecal.solint=10
MSReader
  input MS:       /data2/rvweeren/DR2selfcal/testsing/test.ms
  band            0
  startchan:      0  (0)
  nchan:          120  (0)
  ncorrelations:  4
  nbaselines:     1891
  ntimes:         1798
  time interval:  16.0222
  DATA column:    DATA
  WEIGHT column:  WEIGHT_SPECTRUM
  autoweight:     false
DDECal ddecal.
  H5Parm:              templatejones.h5
  solint:              10
  nchan:               1
  directions:          [[]]
  use model column:    true
  tolerance:           0.0001
  max iter:            1
  flag unconverged:    false
     diverged only:    false
  propagate solutions: false
       converged only: false
  detect stalling:     true
  step size:           0.2
  mode (constraints):  complexgain
  coreconstraint:      0
  smoothnessconstraint:0
  approximate fitter:  false
  subtract model:      false
MSUpdater msout.
  MS:             /data2/rvweeren/DR2selfcal/testsing/test.ms
  datacolumn:     DATA
  weightcolumn    WEIGHT_SPECTRUM
  Compressed:     no

  flush:          0

Processing 1798 time slots ...

0%OpenBLAS : Program will terminate because you tried to start too many threads.
OpenBLAS : Program will terminate because you tried to start too many threads.
OpenBLAS : Program will terminate because you tried to start too many threads.
Segmentation fault

```

**Comment by aroffringa** [comment]
This is more an issue with OpenBLAS than with DP3; see e.g. https://github.com/xianyi/OpenBLAS/issues/1735 . One of the solutions I see there is to build OpenBLAS without multithreading. Because DP3 already does the multi-threading, blas doesn't need to be doing that on top of that to use all cpus. If multi-threading is enabled in blas, it apparently can't handle that it is being called from multiple threads at the same time. Also if you look at that link, certain versions seem affected and others (maybe) not...

**Comment by tammojan** [comment]
As mentioned in the ticket that André refers to, you could try setting the environment variable `OPENBLAS_NUM_THREADS=1`.

**Comment by aroffringa** [comment]
( @tammojan according to rvweeren's report that didn't work )

**Comment by rvweeren** [comment]
@tammojan, we already tried` OPENBLAS_NUM_THREADS=1`, see my first post :-)

**Comment by tikk3r** [comment]
Strangely enough, this issue does not pop up on all machines it seems. I found what @aroffringa refers to today as well, and it so happens to be that I'm indeed (still) using OpenBLAS 0.3.2. They reverted the change in newer version again, I will try updating to the latest version to see if this fixes it.

**Comment by tikk3r** [comment]
Updating OpenBLAS (which reverts the above mentioned changes) has fixed the issue for us. This can probably be closed now.
