### ISSUE TITLE
Error in HDF5

### ISSUE THREAD

**Issue by amisk** [lofar-astron/DP3#133]
Hi,

I am trying to do the initial subtract prefactor run, and this is what I get ...

```
2019-03-22 13:56:11 WARNING node.slurm17.executable_args.L645473_SB000_uv_12BC02481t_179MHz.pre-cal.ms: /opt/soft/lofar-stuff/bin/NDPPP stderr: HDF5-DIAG: Error detected in HDF5 (1.8.16) thread 140286168981376:
  #000: ../../../src/H5G.c line 467 in H5Gopen2(): unable to open group
    major: Symbol table
    minor: Can't open object
  #001: ../../../src/H5Gint.c line 320 in H5G__open_name(): group not found
    major: Symbol table
    minor: Object not found
  #002: ../../../src/H5Gloc.c line 430 in H5G_loc_find(): can't find object
    major: Symbol table
    minor: Object not found
  #003: ../../../src/H5Gtraverse.c line 861 in H5G_traverse(): internal path traversal failed
    major: Symbol table
    minor: Object not found
  #004: ../../../src/H5Gtraverse.c line 641 in H5G_traverse_real(): traversal operator failed
    major: Symbol table
    minor: Callback failed
  #005: ../../../src/H5Gloc.c line 385 in H5G_loc_find_cb(): object 'target' doesn't exist
    major: Symbol table
    minor: Object not found
terminate called after throwing an instance of 'H5::FileIException'

```

I use a DP3 version that is maybe two months old. I created a symlink do have NDPPP, since prefactor has this hardcoded.

Any ideas?
Thx.

**Comment by darafferty** [comment]
I'm not sure about the error above, but I may be able to help with prefactor: which version of prefactor are you using? I ask because the initial subtract pipeline of prefactor v3.0 no longer requires the h5parm.

**Comment by aroffringa** [comment]
I think the mostly likely cause is mixing of HDF5 library versions, e.g. installing a newer version of HDF5 without recompiling DP3 or wrong headers with different library files.

**Comment by tikk3r** [comment]
```
#005: ../../../src/H5Gloc.c line 385 in H5G_loc_find_cb(): object 'target' doesn't exist
```
One of the above, or you might be missing the `target` solset (maybe it's named differently, if you used an older commit of prefactor).

**Comment by amisk** [comment]
The installation of DP3 is from march 4th, prefactor is about a week older. I checked out the master branches and ran the calibrator and target pipelines.

**Comment by amisk** [comment]
I tried something else. I was not sure which cal solutions have to be provided. Before, I provided the same as for the target pipeline, but in the results directory of that, there is also a solutions.h5. So now I supplied this file. Now target is apparently found, but I get `std exception detected: SolTab phase000 does not exist in solset target`.

**Comment by darafferty** [comment]
Ah -- the initial subtract pipeline was changed on March 4th to make it compatible with the target pipeline, so indeed your version won't work. If you get the latest version of the initial subtract parset, it should work fine.

**Comment by amisk** [comment]
I tried it yesterday on the previous data, and that did not work. I'm running the calibrator and then the target pipeline now again just to be sure.

**Comment by aroffringa** [comment]
@amisk is this still an issue?

**Comment by amisk** [comment]
Hey,

I did not encounter this since then... I think it's save to close this.

**Comment by aroffringa** [comment]
Thanks!
