### ISSUE TITLE
"direction" is ignored in applycal substep of predict

### ISSUE THREAD

**Issue by revoltek** [lofar-astron/DP3#136]
I tried to run a parset with:
msin = xxx.MS
msin.datacolumn = DATA
msout = .
msout.datacolumn = MODEL_DATA
steps = [pre]
pre.type = predict
pre.sourcedb = xxx
pre.sources = xxx
pre.operation=add
pre.applycal.h5parm=xxx.h5
pre.applycal.direction=[xxx]

but the "direction" seems ignored. Also all the applycal substep options do not appear in the logs (they do not seem ignored as only "direction" spawn the warning).

**Comment by aroffringa** [comment]
applycal doesn't have a parameter `h5parm`, it's `parmdb`. The logic in Predict.cc is:
https://github.com/lofar-astron/DP3/blob/016e5e58f25d16443c51e44cfa5b432d4969f975/DPPP/Predict.cc#L141

    if (parset.isDefined(prefix + "applycal.parmdb") ||
          parset.isDefined(prefix + "applycal.steps"))
        setApplyCal(input, parset, prefix + "applycal.");
    } else {
        itsDoApplyCal=false;
    }

so if only h5parm is set, it won't do an applycal step. Strange there's no warning about h5parm...

**Comment by revoltek** [comment]
Thanks, I got confused with the h5parm/parmdb parameters. I will correct my code.
