### ISSUE TITLE
Specify station names in coreconstraint

### ISSUE THREAD

**Issue by revoltek** [lofar-astron/DP3#140]
It would be useful to have the possibility to specify which station to constraint in the core constraint with a list of station names. Currently one can specify only "meters from the core". This would slightly increase the complexity of the parset for users but it would make the code more flexible allowing strategies where once a station converged to good solutions it is then blocked in further iterations.

**Comment by aroffringa** [comment]
I've done this and made it actually a bit more generic than you are suggesting. I've added a parameter `antennaconstraint`, which takes a list of lists. To just specify one list of antennas that are to be constrained to have the same solution, you can do:

    antennaconstraint = [[CS002HBA0,CS002HBA1,etc.]]

You can also specify multiple lists:

    antennaconstraint = [[CS002HBA0,CS002HBA1],[CS003HBA0,CS003HBA1]]

This will keep CS002HBA0 and CS002HBA1 the same, and independently keep CS003HBA0 and CS003HBA1 the same. This constraint now also works with full Jones & diagonal solutions.

It's currently in branch `antenna-constraint`, see merge request #143 .

**Comment by revoltek** [comment]
Impressive! Many thanks, I will test is as soon as I'm back from my trip.
