### ISSUE TITLE
ddecal.antennaconstraint issue with flagged antennas

### ISSUE THREAD

**Issue by revoltek** [lofar-astron/DP3#147]
I think I see a problem when I "constraint" a flagged antenna, it seems that flags are propagated to all other antennas (also to those that are not constrained in my test).

**Comment by aroffringa** [comment]
Hi @revoltek ; it was one of the common "NaN" problems: the solver can't solve antennas that are completely flagged, and if they are part of the set, the mean of the set is also NaN. I've now taken care of this: antennas that don't have a solve solution are not added into the mean. In other words, this should be fixed now.

**Comment by revoltek** [comment]
thanks a lot :)
