### ISSUE TITLE
Explode step filters wrongly?

### ISSUE THREAD

**Issue by tikk3r** [lofar-astron/DP3#153]
Trying to split out multiple directions and filtering stations using the `explode` step seems to do something strange with the filtering. Running
```
msin.ntimes=200    
msout.storagemanager = dysco    
    
steps = [explode]    
explode.steps = [shift, adder, filter, avg2, msout]    
explode.replaceparms = [shift.phasecenter, msout.name]    
    
shift.type = phaseshift    
shift.phasecenter=[[163.026994deg,57.685891deg],[162.839619deg,58.446268deg]] 
    
adder.type = stationadder    
adder.stations = {ST001:'CS*'}    
    
filter.type = filter    
filter.baseline=!CS*&&*    
filter.remove = True    
    
avg2.type = average    
avg2.timestep = 2    
avg2.freqstep = 2    
    
msout.overwrite = True    
msout.name = [P3.ms, P42.ms] 
```
gives me a measurement set with only CS stations present, whereas running

```
msin.ntimes=200

msout=P3.superstation.ms
msout.storagemanager=dysco

steps=[shift,adder,filter,averager]

shift.type=phaseshift
shift.phasecenter=[163.026994deg,57.685891deg]

adder.type=stationadder
adder.stations={ST001:'CS*'}

filter.type=filter
filter.baseline=!CS*&&*
filter.remove=True

averager.type=averager
averager.freqstep=2
averager.timestep=2
```
gives me the expected output: a MS with only remote and international stations and the ST001 station.

**Comment by rvweeren** [comment]
@tikk3r , what happens if you put the filter step last?

**Comment by tikk3r** [comment]
Same result putting filter as second last (it has to come before the msout step).

**Comment by tammojan** [comment]
Thanks, I can reproduce this and have it almost fixed. Problem is I forgot to implement the method `addToMS` to the Split step. Expect a fix this week.

**Comment by tikk3r** [comment]
Just gave the `splitaddtoms` branch a try and the above test case works now, awesome.
