### ISSUE TITLE
std exception in explode

### ISSUE THREAD

**Issue by tikk3r** [lofar-astron/DP3#177]
I was trying some things with the explode step, shifting to various directions, and sometimes I run into this error:
```
...
Finished preparing output MS
 copying info and subtables ...

std exception detected: (/opt/lofar/casacore/src/casa/OS/Directory.cc : 304) Failed AlwaysAssert system(command.chars()) == 0
```
It was running on blocks of 10 SB concatenated together at 16ch/2s resolution. It ran fine on 5 directions. Trying 18 directions, this error occured on only 4 out of 25 blocks. I was thinking that maybe it would be a memory issue, since it only happens for a few, but I do not see the node memory being exceeded (~300/368 GB used with 6 DP3's running on a different block).

I have not yet found a consistent way to reproduce it, but maybe you have seen it before? I'm not sure what this assert checks for.

Or is it a casacore issue? I'm using 2.4.1 at the moment.

**Comment by aroffringa** [comment]
Blegh how ugly of casacore; I had a look at the casacore code, and this exception means that casacore tried to copy a directory, and that running `cp -r` returned an error. Could be for many things though; out of disk space, directory did not exist, output dir already existed, etc.

**Comment by tikk3r** [comment]
Ah ok. I've relaunched the 4 that crashed and I'll keep an eye on memory and disk usage to see if something is reaching its limits.

**Comment by aroffringa** [comment]
Since this was a genuine error, but somewhat poorly reported by casacore (and fixed there), I'll close this bug here.
