### ISSUE TITLE
BLAS error tried to allocate too many memory regions

### ISSUE THREAD

**Issue by rvweeren** [lofar-astron/DP3#197]
We are getting this weird error BLAS error in Leiden.

"Program is Terminated. Because you tried to allocate too many memory regions."

For full output and settings used, see below

Increasing nchan=1 to nchan=4 makes the error go away. Somehow it seems to be an issue with the threading (with nchan=4 memory usage is very low so it  is not running out of RAM).

```
"ddecal_init.pset" 12L, 285C written
Singularity lofar_sksp_ddf.simg:/data1/groeneveld/LB_295_10/parsets> DPPP ddecal_init.pset
MSReader
  input MS:       /data1/groeneveld/LB_295_10/SB430_439.superavg.ms
  band            0
  startchan:      0  (0)
  nchan:          80  (0)
  ncorrelations:  4
  nbaselines:     1275
  first time:     2017/04/06/21:00:02
  last time:      2017/04/07/00:59:58
  ntimes:         3595
  time interval:  4.00556
  DATA column:    DATA
  WEIGHT column:  WEIGHT_SPECTRUM
  autoweight:     false
DDECal ddecal.
  H5Parm:              ../SB430_439.superavg.ms/instrument.h5
  solint:              1
  nchan:               1
  directions:          [[]]
  use model column:    true
  tolerance:           0.0001
  max iter:            150
  flag unconverged:    false
     diverged only:    false
  propagate solutions: false
       converged only: false
  detect stalling:     true
  step size:           0.2
  mode (constraints):  phaseonly
  approximate fitter:  false
  only predict:        false
  subtract model:      false
MSUpdater msout.
  MS:             /data1/groeneveld/LB_295_10/SB430_439.superavg.ms
  datacolumn:     CORRECTED_DATA  (has been added to the MS)
  weightcolumn    WEIGHT_SPECTRUM
  writing:        data
  Compressed:     no

  flush:          0

Processing 3595 time slots ...

0%BLAS : Program is Terminated. Because you tried to allocate too many memory regions.
BLAS : Program is Terminated. Because you tried to allocate too many memory regions.
BLAS : Program is Terminated. Because you tried to allocate too many memory regions.
BLAS : Program is Terminated. Because you tried to allocate too many memory regions.
BLAS : Program is Terminated. Because you tried to allocate too many memory regions.
BLAS : Program is Terminated. Because you tried to allocate too many memory regions.
Segmentation fault
```

**Comment by aroffringa** [comment]
There's a FAQ about this question here:
https://github.com/xianyi/OpenBLAS/wiki/faq#allocmorebuffers

It has to do with how you have built OpenBLAS, in particular related to how it is compiled with multi-threading support.

**Comment by rvweeren** [comment]
@aroffringa thanks so it seems it was an issue on our side.

@tikk3r I guess we need to fix  this in the singularity image (surprised we did not run into this earlier).

**Comment by tikk3r** [comment]
I'll look into it. Perhaps you can try changing `OPENBLAS_NUM_THREADS` and/or `OPENBLAS_MAX_THREADS` in the mean time, depending on which version of the image you are using.

**Comment by rvweeren** [comment]
@tikk3r, both OPENBLAS_NUM_THREADS and OPENBLAS_MAX_THREADS are set at 1 in your singularity image.

**Comment by tikk3r** [comment]
> @tikk3r, both OPENBLAS_NUM_THREADS and OPENBLAS_MAX_THREADS are set at 1 in your singularity image.

Yes that was intentional. Try setting it to a higher number (e.g. the numer of CPUs on the node).

**Comment by tikk3r** [comment]
I can reproduce it and am rebuilding the images explicitely specifying more cores for OpenBLAS. In the mean time, a workaround appears to be to add a `numthreads = XX` to the parset. I tried 32, and it seems to work.

**Comment by aroffringa** [comment]
Can this ticket be closed?

**Comment by tikk3r** [comment]
> Can this ticket be closed?

I think so. It's not an DP3 issue in any case.

**Comment by aroffringa** [comment]
Thanks.
