### ISSUE TITLE
Enable tests

### ISSUE THREAD

**Issue by aroffringa** [lofar-astron/DP3#2]
Because the tests depend on the LOFAR CMake macros, they have been disabled for now. They should be changed to work within the new environment (possibly with some rewritten existing macros from LOFAR? Or using a new testing platform?)

**Comment by aroffringa** [comment]
First part of this ticket was fixed in #145 .

**Comment by mnijhuis-tos** [comment]
Since all tests are currently enabled at the main DP3 repository (https://git.astron.nl/RD/DP3), I'm closing this 6-year old issue.
