### ISSUE TITLE
DDECAL: direction dependant solint

### ISSUE THREAD

**Issue by flomertens** [lofar-astron/DP3#209]
The solution interval in which one can solve dependent very much on the SNR in this direction. When solving with very heterogeneous directions (e.g. a high SNR direction with a very bright source and lower SNR direction with a bunch of point sources) it would be nice to be able to have different solution interval for the different direction.

**Comment by aroffringa** [comment]
This has been implemented in the direction-iterative solver algorithm. See https://www.astron.nl/citt/DP3/steps/DDECal.html#solutions-per-direction .

**Comment by aroffringa** [comment]
For reference, there are several associated MRs the last two were:
* https://git.astron.nl/RD/DP3/-/merge_requests/607
* https://git.astron.nl/RD/DP3/-/merge_requests/600
