### ISSUE TITLE
XX is outside 4-byte uint range

### ISSUE THREAD

**Issue by darafferty** [lofar-astron/DP3#22]
When trying to do an averager step with freqstep=6, I get the error "6 is outside 4-byte uint range". I traced the message to line 385 of https://github.com/lofar-astron/DP3/blob/master/Common/StringUtil.cc. Changing the `<` to `>` fixed it, but I'm not sure this is really the correct fix.

**Comment by tammojan** [comment]
Could it be that the 6 you typed is actually a nasty Unicode character way up in the unicode table? Or perhaps you surrounded it by curly quotes?

**Comment by aroffringa** [comment]
No, I converted an assert incorrectly. The fix by @darafferty is correct, I'll create a pull request.

**Comment by aroffringa** [comment]
Push request is there :). Thanks for the detailed report, @darafferty !
