### ISSUE TITLE
Detection of EveryBeam

### ISSUE THREAD

**Issue by AlexKurek** [lofar-astron/DP3#284]
As reported here:
https://git.astron.nl/RD/EveryBeam/-/issues/40#note_4085

If I install like this:

```
mkdir -p ${INSTALLDIR}/EverBeam/build/
cd ${INSTALLDIR}/EverBeam/build/
git clone https://git.astron.nl/RD/EveryBeam.git src/
cmake -DCMAKE_INSTALL_PREFIX=${INSTALLDIR}/EverBeam/ -DCASACORE_ROOT_DIR=${INSTALLDIR}/casacore/ src/
make -j ${J}
make install
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${INSTALLDIR}/EverBeam/lib/
```
EveryBeam will not by detected dy DP3, unless I set `-DEVERYBEAM_LIB=${INSTALLDIR}/EverBeam/lib/` in DP3's cmake.

**Comment by jmmaljaars** [comment]
Thanks again for reporting. This issue is only relevant for the DP3/development branch and we definitely will fix it once we get closer to a new DP3 release. As a work-around, just add the EveryBeam install directory to your DP3 CMAKE_PREFIX_PATH if you want to build DP3/development.
