### ISSUE TITLE
Fulljones applycal flags international stations

### ISSUE THREAD

**Issue by tikk3r** [lofar-astron/DP3#311]
For widefield long baseline stuff we use killMS solutions at one point, which are fulljones. Before applying them they are converted to h5parm and the international stations are added with amplitudes of 1 and phases of 0, as they don't exist in the killMS solutions.

The resulting h5parm looks ok to me (amp and phase are 1 and 0 for international stations), but applying it results in all baselines with international stations getting flagged. They do not get flagged if just XX and YY are taken from the killMS solutions and processed the same way and applied as normal diagonal phase and amplitude solutions.

Is there a detail about fulljones solutions that I'm perhaps overlooking?

**Comment by tammojan** [comment]
I don't think there are details. If you could provide a test MS + h5parm, we could dive into it.

**Comment by tikk3r** [comment]
I have put a small chunk of the MS, the relevant h5parm and parset here: https://public.spider.surfsara.nl/project/lofarvwf/fulljones_mwe.tar

**Comment by tikk3r** [comment]
After insightful discussion with @rvweeren, it turns out this is not an issue with DP3, but a misunderstanding of the cross-hand gains on my part. When adding dummy entries the gain amplitudes for XY and YX should be set to 0, not 1.

**Comment by tammojan** [comment]
That is correct. Thanks for reporting back. Sorry, I hadn't noticed it yet in the files you sent. Glad it works now!
