### ISSUE TITLE
DP3v5 fails in concatenating datasets

### ISSUE THREAD

**Issue by revoltek** [lofar-astron/DP3#318]
This command used to work ok in DP3v4:
`DPPP DPPP-concat.parset msin="[a399-a401_SB155.MS,a399-a401_SB156.MS,a399-a401_SB157.MS,a399-a401_SB158.MS,a399-a401_SB159.MS,a399-a401_SB160.MS,a399-a401_SB161.MS,a399-a401_SB162.MS,a399-a401_SB163.MS,a399-a401_SB164.MS,a399-a401_SB165.MS,a399-a401_SB166.MS,a399-a401_SB167.MS,a399-a401_SB168.MS,a399-a401_SB169.MS,a399-a401_SB170.MS,a399-a401_SB171.MS,a399-a401_SB172.MS,a399-a401_SB173.MS,a399-a401_SB174.MS,a399-a401_SB175.MS,a399-a401_SB176.MS,a399-a401_SB177.MS,a399-a401_SB178.MS,a399-a401_SB179.MS,a399-a401_SB180.MS,a399-a401_SB181.MS,a399-a401_SB182.MS,a399-a401_SB183.MS,a399-a401_SB184.MS,a399-a401_SB185.MS,a399-a401_SB186.MS,a399-a401_SB187.MS,a399-a401_SB188.MS,a399-a401_SB189.MS,a399-a401_SB190.MS,a399-a401_SB191.MS,a399-a401_SB192.MS,a399-a401_SB193.MS,a399-a401_SB194.MS,a399-a401_SB195.MS,a399-a401_SB196.MS,a399-a401_SB197.MS,a399-a401_SB198.MS,a399-a401_SB199.MS,a399-a401_SB200.MS,a399-a401_SB201.MS,a399-a401_SB202.MS,a399-a401_SB203.MS,a399-a401_SB204.MS,a399-a401_SB205.MS,a399-a401_SB206.MS,a399-a401_SB207.MS,a399-a401_SB208.MS,a399-a401_SB209.MS,a399-a401_SB210.MS,a399-a401_SB211.MS,a399-a401_SB212.MS,a399-a401_SB213.MS,a399-a401_SB214.MS,a399-a401_SB215.MS,a399-a401_SB216.MS,a399-a401_SB217.MS,a399-a401_SB218.MS,a399-a401_SB219.MS,a399-a401_SB220.MS,a399-a401_SB221.MS,a399-a401_SB222.MS,a399-a401_SB223.MS,a399-a401_SB224.MS,a399-a401_SB225.MS,a399-a401_SB226.MS,a399-a401_SB227.MS,a399-a401_SB228.MS,a399-a401_SB229.MS,a399-a401_SB230.MS,a399-a401_SB231.MS,a399-a401_SB232.MS,a399-a401_SB233.MS,a399-a401_SB234.MS,a399-a401_SB235.MS,a399-a401_SB236.MS,a399-a401_SB237.MS,a399-a401_SB238.MS,a399-a401_SB239.MS,a399-a401_SB240.MS,a399-a401_SB241.MS,a399-a401_SB242.MS,a399-a401_SB243.MS,a399-a401_SB244.MS,a399-a401_SB245.MS,a399-a401_SB246.MS,a399-a401_SB247.MS,a399-a401_SB248.MS,a399-a401_SB249.MS,a399-a401_SB250.MS,a399-a401_SB251.MS,a399-a401_SB252.MS,a399-a401_SB253.MS,a399-a401_SB254.MS,a399-a401_SB255.MS,a399-a401_SB256.MS,a399-a401_SB257.MS,a399-a401_SB258.MS,a399-a401_SB259.MS,a399-a401_SB260.MS,a399-a401_SB261.MS,a399-a401_SB262.MS,a399-a401_SB263.MS,a399-a401_SB264.MS,a399-a401_SB265.MS,a399-a401_SB266.MS,a399-a401_SB267.MS,a399-a401_SB268.MS,a399-a401_SB269.MS,a399-a401_SB270.MS,a399-a401_SB271.MS,a399-a401_SB272.MS,a399-a401_SB273.MS,a399-a401_SB274.MS,a399-a401_SB275.MS,a399-a401_SB276.MS,a399-a401_SB277.MS,a399-a401_SB278.MS,a399-a401_SB279.MS,a399-a401_SB280.MS,a399-a401_SB281.MS,a399-a401_SB282.MS,a399-a401_SB283.MS,a399-a401_SB284.MS,a399-a401_SB285.MS,a399-a401_SB286.MS,a399-a401_SB287.MS,a399-a401_SB288.MS,a399-a401_SB289.MS,a399-a401_SB290.MS,a399-a401_SB291.MS,a399-a401_SB292.MS,a399-a401_SB293.MS,a399-a401_SB294.MS,a399-a401_SB295.MS,a399-a401_SB296.MS,a399-a401_SB297.MS,a399-a401_SB298.MS,a399-a401_SB299.MS,a399-a401_SB300.MS,a399-a401_SB301.MS,a399-a401_SB302.MS,a399-a401_SB303.MS,a399-a401_SB304.MS,a399-a401_SB305.MS,a399-a401_SB306.MS,a399-a401_SB307.MS,a399-a401_SB308.MS,a399-a401_SB309.MS,a399-a401_SB310.MS,a399-a401_SB311.MS,a399-a401_SB312.MS,a399-a401_SB313.MS,a399-a401_SB314.MS,a399-a401_SB315.MS,a399-a401_SB316.MS,a399-a401_SB317.MS,a399-a401_SB318.MS,a399-a401_SB319.MS,a399-a401_SB320.MS,a399-a401_SB321.MS,a399-a401_SB322.MS,a399-a401_SB323.MS,a399-a401_SB324.MS,a399-a401_SB325.MS,a399-a401_SB326.MS,a399-a401_SB327.MS,a399-a401_SB328.MS,a399-a401_SB329.MS,a399-a401_SB330.MS,a399-a401_SB331.MS,a399-a401_SB332.MS,a399-a401_SB333.MS,a399-a401_SB334.MS,a399-a401_SB335.MS,a399-a401_SB336.MS,a399-a401_SB337.MS,a399-a401_SB338.MS,a399-a401_SB339.MS,a399-a401_SB340.MS,a399-a401_SB341.MS,a399-a401_SB342.MS,a399-a401_SB343.MS,a399-a401_SB344.MS,a399-a401_SB345.MS,a399-a401_SB346.MS,a399-a401_SB347.MS,a399-a401_SB348.MS,a399-a401_SB349.MS,a399-a401_SB350.MS,a399-a401_SB351.MS,a399-a401_SB352.MS,a399-a401_SB353.MS,a399-a401_SB354.MS,a399-a401_SB355.MS,a399-a401_SB356.MS,a399-a401_SB357.MS,a399-a401_SB358.MS,a399-a401_SB359.MS,a399-a401_SB360.MS,a399-a401_SB361.MS,a399-a401_SB362.MS,a399-a401_SB363.MS,a399-a401_SB364.MS,a399-a401_SB365.MS,a399-a401_SB366.MS,a399-a401_SB367.MS,a399-a401_SB368.MS,a399-a401_SB369.MS,a399-a401_SB370.MS,a399-a401_SB371.MS,a399-a401_SB372.MS,a399-a401_SB373.MS,a399-a401_SB374.MS,a399-a401_SB375.MS,a399-a401_SB376.MS,a399-a401_SB377.MS,a399-a401_SB378.MS,a399-a401_SB379.MS,a399-a401_SB380.MS,a399-a401_SB381.MS,a399-a401_SB382.MS,a399-a401_SB383.MS,a399-a401_SB384.MS,a399-a401_SB385.MS,a399-a401_SB386.MS,a399-a401_SB387.MS,a399-a401_SB388.MS,a399-a401_SB389.MS,a399-a401_SB390.MS,a399-a401_SB391.MS,a399-a401_SB392.MS,a399-a401_SB393.MS,a399-a401_SB394.MS,a399-a401_SB395.MS,a399-a401_SB396.MS,a399-a401_SB397.MS,a399-a401_SB398.MS]"  msout=mss/mss.MS`

With parset:
```
msin = 
msin.datacolumn = CORRECTED_DATA
msin.baseline = [CR]S*&
msin.missingdata = True
msin.orderms = False

msout = 
msout.writefullresflag = False
msout.storagemanager = dysco

numthreads = 1 # leave this to 1 as it is run with s.run() and io limited

steps = []
```

With DP3v5 the resulting dataset is corrupted:
```
l /data/a499-501/id772883_-_a399-a401/mss/mss.MS/table.f3
-rw-r--r-- 1 fdg users 0 Jan 13 09:17 mss/mss.MS/table.f3
```
(note the 0 byte of the file size)

This is the output (note the 2 missing MSs - maybe the issue is there?)
```
Finished preparing output MS
MultiMSReader
  input MSs:      a399-a401_SB155.MS
                  a399-a401_SB156.MS
                  [...]
                  a399-a401_SB398.MS
  baseline:       [CR]S*&
  band            0
  startchan:      0  (0)
  nchan:          1952  (0) (regularly spaced)
  ncorrelations:  4
  nbaselines:     630
  ntimes:         5393
  time interval:  4.00556
  DATA column:    CORRECTED_DATA
      MS missing         a399-a401_SB326.MS
      MS missing         a399-a401_SB357.MS
  WEIGHT column:  WEIGHT_SPECTRUM
  autoweight:     false
MSWriter msout.
  output MS:      /data/a499-501/id772883_-_a399-a401/mss/mss.MS
  nchan:          1952
  ncorrelations:  4
  nbaselines:     630
  ntimes:         5393
  time interval:  4.00556
  DATA column:    DATA
  WEIGHT column:  WEIGHT_SPECTRUM
  Compressed:     yes
  Data bitrate:   10
  Weight bitrate: 12
  Dysco mode:     AF TruncatedGaussian(2.5)

Processing 5393 time slots ...

0%....10....20....30....40....50....60....70....80....90....100%
Finishing processing ...
```

**Comment by aroffringa** [comment]
Thanks for reporting Francesco, it's on the Schaap's team task list.
 
Maybe this is the result of https://git.astron.nl/RD/DP3/-/merge_requests/324
For the schaap team: If it doesn't exist yet, it would be good to add an integration test that combines measurement sets, including one that has a missing measurement set.

**Comment by henedler** [comment]
I also find (slightly different) issues when concatenating with the newest DP3:

I want to concatenate measurement sets with identical time stamps in the most basic way:
```
msin = ../real/cals-bkp/*SB29*MS
msin.datacolumn = DATA

msout = ./mss/test.MS

steps=[]
```
The resulting measurement set has a reasonable size on the disk, but the columns are all zero. 

```
 copying info and subtables ...
Finished preparing output MS
MultiMSReader
  input MSs:      ../real/cals-bkp/3c196_t201806301100_SB291.MS
                  ../real/cals-bkp/3c196_t201806301100_SB296.MS
                  ../real/cals-bkp/3c196_t201806301100_SB293.MS
                  ../real/cals-bkp/3c196_t201806301100_SB299.MS
                  ../real/cals-bkp/3c196_t201806301100_SB295.MS
                  ../real/cals-bkp/3c196_t201806301100_SB294.MS
                  ../real/cals-bkp/3c196_t201806301100_SB298.MS
                  ../real/cals-bkp/3c196_t201806301100_SB297.MS
                  ../real/cals-bkp/3c196_t201806301100_SB292.MS
                  ../real/cals-bkp/3c196_t201806301100_SB290.MS
  band            0
  startchan:      0  (0)
  nchan:          40  (0) (regularly spaced)
  ncorrelations:  4
  nbaselines:     703
  ntimes:         7190
  time interval:  4.00556
  DATA column:    DATA
  WEIGHT column:  WEIGHT_SPECTRUM
  autoweight:     false
MSWriter msout.
  output MS:      /localwork/henrik/test_ampsols/mss/test.MS
  nchan:          40
  ncorrelations:  4
  nbaselines:     703
  ntimes:         600
  time interval:  4.00556
  DATA column:    DATA
  WEIGHT column:  WEIGHT_SPECTRUM
  Compressed:     no

Processing 600 time slots ...

0%....10....20....30....40....50....60....70....80....90....100%
Finishing processing ...

```

Note that I also get the error described in [#321] after processing is finished, not sure if this is related.
