### ISSUE TITLE
segfault with antenna selection

### ISSUE THREAD

**Issue by revoltek** [lofar-astron/DP3#322]
the following command seems to give a segfault when the msin.baslines are set (otherwise it works)

`DPPP DPPP-solTEC.parset msin=mss/TC07.MS sol.h5parm=mss/TC07.MS/tec1.h5 msin.baseline='[CR]*&&;!RS208LBA;!RS210LBA;!RS307LBA;!RS310LBA;!RS406LBA;!RS407LBA;!RS409LBA;!RS508LBA;!RS509LBA' sol.antennaconstraint=[[CS002LBA,CS003LBA,CS004LBA,CS005LBA,CS006LBA,CS007LBA]] sol.solint=15 sol.nchan=8 numthreads=8`

when using only one station to exclude it dies with:
`0%corrupted size vs. prev_size
Aborted (core dumped)`

the same command was working fine in dp3v4.2

**Comment by tammojan** [comment]
Fixed by c71feae

**Comment by tammojan** [comment]
Note that the issue was introduced in ddf77f7b4f389b07bfae345e6ad0e06db0d95121.
