### ISSUE TITLE
makesourcedb appends skymodel by default

### ISSUE THREAD

**Issue by henedler** [lofar-astron/DP3#324]
According to the [makesourcedb doucmentation](https://www.astron.nl/lofarwiki/doku.php?id=public:user_software:documentation:makesourcedb), the default behaviour when creating a sourcedb that already exists should be to overwrite this sourcedb.

However, it seems that by default, the skymodel is appended when running the same makesourcedb command multiple times.

**Comment by revoltek** [comment]
In general I think the makesourcedb step should be removed and DP3 should read txt skymodels and do the conversion internally
