### ISSUE TITLE
Wrong solutions from DDEcal

### ISSUE THREAD

**Issue by henedler** [lofar-astron/DP3#325]
Collecting the ddecal issues in the current DP3 master reported on slack:

When running a basic solve step, the resulting solutions are wrong in a variety of ways (not all of these may occur simultaneously):
- Amplitudes are very high (~1e16) 
- Phases are either zero or very small 
- The solver stops after a single iteration (only when solving on MODEL_DATA)
- solution weights are very small (only when solving on MODEL_DATA)

For the very same dataset, DP3 version 4.2 produces correct solutions.

Below you can find an example with a small (15MB) dataset. The example also contains h5parm solutions derived with old and current DP3 versions and the DP3 parset to reproduce them.

[minimal_example2.tar.gz](https://github.com/lofar-astron/DP3/files/5971978/minimal_example2.tar.gz)

**Comment by tammojan** [comment]
The third and fourth bullet should be solved with 0cdf916 (which is on master now). It solves an issue with reading the model data column in ddecal.

We'll have another look at bullets 1 and 2.

**Comment by henedler** [comment]
Hi, awesome news. With the minimal example from above, all bullet points appear to be fixed in the current master. Now, the solutions agree with DP3 v4.2. 
I'll close the issue for now, if I encounter bullet 1 or 2 in the future, I'll reopen.

**Comment by aroffringa** [comment]
Great to hear, and thanks a lot for the testing, @henedler !
