### ISSUE TITLE
Applying the beam in ddecal results with NaN entries in the solution database

### ISSUE THREAD

**Issue by shulevski** [lofar-astron/DP3#33]
Setting `usebeammodel=true` in a DDE solve results in an H5 solution file having NaN entries for some values. The h5parmpredict (subtract) then results in sources not being subtracted. Doing the subtraction using DI predict (subtract) seems to work however. 
This is the case when working with AARTFAAC data sets, I have not verified whether it happens for LOFAR data.

**Comment by aroffringa** [comment]
Is this related to `usebeammodel`, or is that just accidentally? NaNs can happen when things don't converge -- you probably want to change settings if that happens...

**Comment by shulevski** [comment]
When `usebeammodel=false`, there are no NaN values, all of the other settings are identical.

**Comment by aroffringa** [comment]
Can you provide a small testset/scenario? This is at this point a bit too vague of a problem to analyse.

**Comment by shulevski** [comment]
I think that this issue can be closed. Above, I commented based on my previous conversation with Tammo Jan who found that all solutions have NaN values then doing a DDE solve. I was using an older version of DPPP then, and I don't know which DPPP version he used. I have updated the DPPP now and I don't see that the solutions are flagged. This is assuming I can trust LoSoTo (output follows):
```
Solution table 'amplitude000' (type: amplitude): 60 times, 3 freqs, 576 ants, 2 dirs, 4 pols
    Flagged data: 0.000%
    History: 02-10-2018 09:36:03: CREATE by DPPP
             DPPP: version = trunk (in CMakeLists.txt: 1.0)
              branch = trunk
              overall revision  = 40908
              package revision  = 40782 (last change in package)
              built on 241aa039fb9a by  at Oct  1 2018 16:39:53
             
             step dcal. in parset: 
             dcal.directions=[[CasA],[CygA]]
             dcal.mode=fulljones
             dcal.nchan=1
             dcal.onebeamperpatch=false
             dcal.solint=1
             dcal.sourcedb=A-team_lowres.sourcedb
             dcal.type=ddecal
             dcal.usebeammodel=true
             dcal.uvlambdamin=10
             msin=SB324-07080120_5m3ch.ms/
             msout=.
             steps=[dcal]
```
