### ISSUE TITLE
Required AOFlagger version

### ISSUE THREAD

**Issue by AlexKurek** [lofar-astron/DP3#332]
Just a tiny report: trying to compile DP3 master  I got an error:

> -- Found an incompatible version of AOFlagger: found 3.0.0, need 3.0.1
> -- Found an incompatible version of AOFlagger: found 3.0.0, need 3.0.1
> CMake Error at CMakeLists.txt:148 (find_package):
>   Could not find a configuration file for package "AOFlagger" that is
>   compatible with requested version "3.0.1".
> 
>   The following configuration files were considered but not accepted:
> 
>     /opt/aoflagger/share/aoflagger/cmake/aoflagger-config.cmake, version: 3.0.0

But it seems there is no 3.0.1 tag:
https://gitlab.com/aroffringa/aoflagger/-/tags
Maybe "3.0.1" is misspelled?

**Comment by aroffringa** [comment]
3.0.1 is just the minimum -- 3.1 will also suffice, which has a tag.

Subminor versions aren't released or tagged. We increase the (subminor) required version in DP3 when we change the interface and DP3 requires that interface, so you don't get a compilation error with older versions. As we don't  immediately release a new aoflagger version, we don't immediately set the requirement to 3.1, so the repositories' masters are still consistent and can be build. Nevertheless, we can set the min requirement now to 3.1 to make this a bit more obvious, I've submitted a MR for this, https://git.astron.nl/RD/DP3/-/merge_requests/552.

**Comment by aroffringa** [comment]
Thanks for the report Alex. I've closed the ticket to keep track of tickets that require work, but if you have more issues feel free to reopen it of course ;).
