### ISSUE TITLE
assert hdr.checkMagicValue fails

### ISSUE THREAD

**Issue by Joshuaalbert** [lofar-astron/DP3#336]
I'm trying to do a `ddecal` step with a simulated measurement set. The MS was created using casa, and filled using wsclean.

## Questions
1. What is the cause of this error code?
2. What would be a suitable method to create (not fill) an MS that DPPP would like?

## Reproducing

Create a MS with CASA and then run this command:

```bash
singularity exec -B /fastpool/albert /fastpool/albert/envs/lofar_sksp_ddf.simg DPPP \
    numthreads=32 \
    msin=W-snapshot-8000chan.ms \
    msin.datacolumn=DATA \
    msout=. \
    steps=[ddecal]  \
    ddecal.type=ddecal \
    ddecal.maxiter=100 \
    ddecal.propagatesolutions=True \
    ddecal.solint=5 \
    ddecal.nchan=1 \
    ddecal.h5parm=solutions.h5 \
    ddecal.sourcedb=single-source.skymodel \
    ddecal.model=complexgains \
    verbose=T
```

I'm getting a magic number error at this line https://github.com/lofar-astron/DP3/blob/master/blob/BlobIStream.cc#L56:
![screenshot_from_2022-04-14_11-53-43](https://user-images.githubusercontent.com/14807032/164118669-ad568374-432e-42a1-9e4f-5ec379ca9e2d.png)

The MS is regular:
![screenshot_from_2022-04-16_13-12-59](https://user-images.githubusercontent.com/14807032/164118701-3971e29b-ac1c-41e6-afd4-79e3dc91a73a.png)

I see that the antenna locations are weird. Would this have an impact?
![screenshot_from_2022-04-16_13-10-40](https://user-images.githubusercontent.com/14807032/164119162-82aab64d-41cf-43d0-938f-6bce8fb11d41.png)

DPPP version `5.1.0`

**Comment by tammojan** [comment]
This means that the skymodel is not recognized. Plain text skymodel loading was introduced in DP3 after the version you're using. It may help to convert the skymodel to a blob sourcedb with `makesourcedb in=single-source.skymodel out=single-source.sourcedb outtype=blob`. Alternatively, build the master branch of DP3 (we haven't made a release with skymodel support yet).

**Comment by Joshuaalbert** [comment]
Thanks Tammo Jan!
