### ISSUE TITLE
DP3 Python bindings and step aggregation.

### ISSUE THREAD

**Issue by abourramouss** [lofar-astron/DP3#341]
Hello everyone,

First a bit of introduction, I am working on distributing DP3 across workers, basically we create partitions using casacore and distribute the computational load  and data of different steps across workers. We're working on dynamic partitioning tools for measurement sets to efficiently distribute data.

I have seen that there are python bindings for DP3, I am currently wrapping the DP3  and calling it as a subprocess with python passing the parameters specified by the user via a dictionary and converting them to a parset, I haven't found much documentation or code examples for the bindings.

For step aggregation, I have some cases where it works, for example for a rebinning step there's: "_steps": "[aoflag, avg, count]"._

But for example, i would like to join multiple steps into a single one without creating a new one, for example i would like to join the cal and sub steps, but since there's a _cal.h5parm_ and a _sub.applycal.parmdb_ that depend on each other, it doesn't work. The error that i get from dp3 when trying to create a combined cal and sub is:

_std exception detected: SolTab amplitude000 does not exist in solset sol000_

**Comment by tammojan** [comment]
With the current implementation, the h5parm file is written only at the end of all processing, so cannot be used in subsequent applycal step. However, if you use DDECals' option `storebuffer` the solutions are stored in the buffer and can be used in applycal.

**Comment by abourramouss** [comment]
> With the current implementation, the h5parm file is written only at the end of all processing, so cannot be used in subsequent applycal step. However, if you use DDECals' option `storebuffer` the solutions are stored in the buffer and can be used in applycal.

Thanks for the response!

as per python bindings, is there any documentation or code examples? that would come in handy.
