### ISSUE TITLE
shared library SOVERSION missing

### ISSUE THREAD

**Issue by gijzelaerr** [lofar-astron/DP3#43]
For the lofar software I manually patched that for a while:

https://github.com/kernsuite-debian/lofar/blob/master/debian/patches/soversion

Would be nice if this finally lands upstream.

**Comment by aroffringa** [comment]
I'm not sure what you want, but I'm happy to apply a patch.

**Comment by gijzelaerr** [comment]
basically, just the SOVERSION needs to be set for all library products. For historical reasons, it is probably best to start numbering at 2. I'm not sure if this patch applies cleanly, i'll have a look later today.

**Comment by gijzelaerr** [comment]
hm, i don't see any shared libraries being installed anymore? Was i confused?

**Comment by aroffringa** [comment]
No, we now compile them right into DP3, because some platforms wouldn't load the dynamic libraries under certain circumstances, but we did not do that yet before.
