### ISSUE TITLE
DPPP doesn't write flags in h5parm

### ISSUE THREAD

**Issue by revoltek** [lofar-astron/DP3#44]
Some combinations of solver+mode do not properly handle flags (i.e. the solver doesn't write any flag). So far I noticed it in DDE+diag and in DIE+fulljones. A check of all modes in both solvers should be done to be sure that flags are always properly saved in h5parms.

At the same time, it would be good to also check if applycal properly propagates all flags back to the MS, this was not the case for a few modes, but needs to be there for all of them.

**Comment by aroffringa** [comment]
What do you mean with flags in h5parm: solution with zero weight or NaN value?

**Comment by revoltek** [comment]
The problem is that flagged solutions are (in certain cases) set to nan in the h5parm but the corresponding weights is !=0

**Comment by revoltek** [comment]
hum, that is something to discuss, I agree. But it would require some major change in the way h5parms are used. So fare we have always assumed that weight=0 is a flagged data. Now to use dppp-generated h5parms we need to manually set to weight=0 those nans.

**Comment by aroffringa** [comment]
Sure it would be good / I'm happy to make things somewhat more consistent. But in any case, I think that both a NaN and weight=0 should imply that the solution is flagged -- I think that makes sense in any case, and it should be easy to adapt Losoto to that concept, isn't it?

**Comment by revoltek** [comment]
I've updated the H5parm_collector to set weight=0 for nans as a temporary workaround. I understand the point of keeping the weights also for flagged data, this would also speed up some operations as the weights would became essentially unused in most operations and fetching the data would fetch also the flags. But if we change this thing we need a coordinated effort and a new release of losoto.

**Comment by tammojan** [comment]
I'm not aware of the logic that André mentions. So I would be surprised if this is the logic that I implemented. In my view, flag==0 and weight==NaN is exactly the same.

**Comment by revoltek** [comment]
weights is always != NaN, data can be == NaN. The main difference is that now when data == NaN also weight == 0. In the logic Andre' suggested this might not be the case. For losoto this implies some work to do as flags would be np.where(data==nan) and not np.where(weights==0). I must say that insofar we have no use whatsoever of the weights in the solutions (and no plans to use them in the short term).

**Comment by aroffringa** [comment]
I'm not sure we are all talking about the same things. What @revoltek implemented as what he calls the "temporary workaround" seems fine to me and more or less what I suggested: both zero weight and NaNs are to be considered as flagged samples by Losoto. The weights might currently be not so used, but I think they could definitely be useful for certain things (fitting things within Losoto would probably already use benefit from this). I wasn't suggesting to remove those from the hdf5.

**Comment by revoltek** [comment]
The workaround I've now works if the h5parm goes through the collector, which is not always the case. I think we need a more definitive+clean solution. But I need to know how you decide to harmonize dppp behavior.

**Comment by aroffringa** [comment]
I think the definitive solution is to always assume that solutions might be NaN. While I could change DPPP to always set weight=0 when storing a NaN, there could be usecases that this is not desirable.

**Comment by revoltek** [comment]
Then dppp needs to always put nans for flagged data, is it currently the case? If it is I will put as losoto3 milestone to have flags implemented in this way.

**Comment by aroffringa** [comment]
DPPP doesn't do that, and it's not necessary either; if you just assume that both a zero weight and a NaN implies bad data, then that works. That way, we can reserve them for having different meanings.

**Comment by revoltek** [comment]
Conclusion: DPPP needs to harmonize the output of weights+data across the different operation. Both nans and weights=0 are "flags" with different meanings.

**Comment by revoltek** [comment]
This thing is driving me crazy :) the possibility of having weight != 0 and vals=nan in solutions creates a number of problems in losoto. Fixing them is possible (but it requires a major rewriting as this was not in the h5parm specification) + it would make the software way slower (every time one needs to check flags 2 large arrays needs to be parsed instead of 1). I'd really like to have DPPP consistent with h5parm specification where all flagged data must have weights=0.

**Comment by revoltek** [comment]
I'd like to release a 3.0 of losoto soon, fixing this (e.g. adding a check that for every solution written in the h5parm that is nan then put the weight to 0) would allow me to clean up a lot of ugly patches I did to consider all cases in all operations.

**Comment by aroffringa** [comment]
I don't have time to fix this, because I'm not familiar with the solution stuff and don't want to invest in that. I hope that Tammo Jan takes this up at some point, but as you know he's not officially on DP3 right now.

Please don't litter the tickets with multiple requests to re-prioritize a request, that's not helping.
