### ISSUE TITLE
Add keywords that describe how beam is applied

### ISSUE THREAD

**Issue by aroffringa** [lofar-astron/DP3#60]
This is really necessary to avoid people apply incorrect beams (i.e. fuil instead of differential), which I unfortunately see happening a lot!

**Comment by tammojan** [comment]
It would be good to register here also the name ('hamaker-arts') and version of the beam model applied.

**Comment by aroffringa** [comment]
I think that's less crucial. When we have multiple versions of the beam, we could always add those fields without breaking backward compatibility (everything that has beam keywords is assumed to have the version of the beam that we have now). I think we're a bit overdesigning when we're adding those now already...

**Comment by aroffringa** [comment]
Fixed in #77 .
