### ISSUE TITLE
Segmentation fault on just "DPPP"

### ISSUE THREAD

**Issue by tikk3r** [lofar-astron/DP3#66]
I just tried to build it in Leiden and I get a segfault when running just `DPPP`. Other things like `DPPP -v` (returns DPPP 0.0), `DPPP -h` and a simple `DPPP msin=ms1.ms msout=ms2.ms steps=[]` all seem to work though (haven't used it on heavier tasks yet).

**Comment by aroffringa** [comment]
I can't reproduce this, it turns fine for me. Also a valgrind with only the DPPP command doesn't show any incorrect mem access. It might have to do with environment or setup.

**Comment by tikk3r** [comment]
Yes of course, thanks for the tip. I will poke around a bit more to see if I can find something.

**Comment by tikk3r** [comment]
Posting this just for reference, it was indeed my environment/setup. It seems that a too new Boost version was causing the issue. I used 1.63.0 for my install, since that seemd to solve an unrelated problem in the past, and never thought about it again.

Running it with gdb showed the segfault was related to something regarding `boost::filesystem::detail::status` (that's all it gave). Going back to version 1.58.0, running just `DPPP` prints out the help message without any errors. Sorry for the trouble.

**Comment by aroffringa** [comment]
Thanks for letting us know, that's good to know. I think your boost 1.63 must have been installed incorrectly -- I use currently 1.67 without problems.
