### ISSUE TITLE
taking out the beam on phase shifted data

### ISSUE THREAD

**Issue by rvweeren** [lofar-astron/DP3#68]
I phase shifted my data almost to the FWHM of the station beam. Then I want to take out the beam (array_factor since the original data was already corrected in the phase center with the element beam) like this:

NDPPP msin=phaseshifted.ms msout=out.ms steps=[ab] ab.type=applybeam ab.usechannelfreq=true ab.beammode=array_factor ab.updateweights=true

As I understand things, NDPPP now should take out the beam (array factor part) in the -current- phase center of the ms. However, almost nothing changes when I make an image. While I should see the my fluxes go up by a factor > 2. Seems like this step is broken and it does not correctly pick up the phase center??

**Comment by rvweeren** [comment]
I currently use https://github.com/revoltek/losoto/blob/master/losoto/operations/lofarbeam.py as a workaround (losoto computes the array_factor (via lofar.stationresponse) at the location of the current phase center and then losoto fills a H5 solutions file with the "beam gains", this h5 can then be applied with dp3)

Regarding the "use-differential-beam" I assumed that this always referred to the delay centre (that was our original idea to always, by default, correct for the element beam in the delay center/ref centre as the first step in all processing). When I made images with IDG (I phase-shifted)  it seemed that it work that way and my images came out fine with more or less correct fluxes around the FWHM....maybe because the main correction is the array factor here and WSClean still corrects for that one based on the delay_dir? (and it does not assume the array_factor is already taken out on the current phase dir, otherwise I cannot explain why my fluxes are correct...)

**Comment by aroffringa** [comment]
I checked it again, but IDG's differential beam correction really corrects the differential part from phase centre to actual image position, and not from delay centre to image position. As far as I see, if you would phase shift to the FWHM, then apply the beam with DP3 (or the other way around -- doesn't matter), and then run wsclean with differential beam, your image should be off by a factor of 2. If you're sure that's not the case then I'm not understanding something...

**Comment by rvweeren** [comment]
Hmm, I need to double check.

**Comment by rvweeren** [comment]
@aroffringa, I had a look and WSClean-IDG seems to fully corrects for the array_factor on the new phase center with use-differential-lofar-beam. (and that correction is not(!) 1.0 in the current phase center of a phase shifted dataset)

It looks like the "use-differential-lofar-beam" just assumes -only- the element beam is taken out (that was also the original idea of the usage of this functionally in awimager). Now the element beam is almost the same on the delay center as it is on a new phase center (if you just shift by a few degr). With "use-differential-lofar-beam"  WSClean then still then fully corrects for the array_factor of the beam, based on the delay_center and new phase center. Meaning that the fluxes that come out on phase shifted data substantially change (for example by a factor of two if you phase-shift to the FWHM of the station beam). That is also what I see happening, see the attached image. Left IDG-corrected (with use-differential-lofar-beam) image (at phase-center of a phase-shifted dataset). Right image without any beam correction. I phase-shifted to about the FWHM. Note the clear upscale of the pixel values.

![idg](https://user-images.githubusercontent.com/3879473/48137000-55afd980-e2a1-11e8-97ad-d735403a612b.jpg)

>I checked it again, but IDG's differential beam correction really corrects the differential part from phase centre to actual image position, and not from delay centre to image position. 

So I think what you said here must(?) only refer to the element beam, otherwise I cannot exlain my results.

**Comment by aroffringa** [comment]
Ok seems like I'm confused. I've confused REFERENCE_DIR and PHASE_DIR... It's true that WSClean doesn't use DELAY_DIR, as I mentioned, but it does use REFERENCE_DIR and not PHASE_DIR. DPPP uses DELAY_DIR, which is probably in most cases equal to PHASE_DIR, although they have slightly different meanings, and I'm not completely sure LOFAR's correlator matches these two in all cases. 

REFERENCE_DIR doesn't change when changing the phase centre, so then -- by accident I must say -- even when changing the phase centre, fluxes should come out correctly. Apologies for my change of opinion ;).

WSClean always calculates "full" beams, not just an array factor or element beam. When asking for the differential beam, it assumes the full beam has been applied at the centre, and applies the full beam difference to the rest of the field. So when imaging with WSClean, only the full beam should be applied in DP3 (which I guess is only relevant when changing phase centres, but nevertheless probably a good rule in any case).

**Comment by aroffringa** [comment]
Hi @rvweeren -- it's good that I at least now understand what happens in DP3/wsclean :) but I'm not sure if there's anything to do? Do we need to change the way this behaves, or is all that's necessary covered by #60 ?

**Comment by rvweeren** [comment]
We still miss the option to take out ("correct") the beam in NDPPP in an arbitrary direction.
According to @tammojan, NDPPP can only do it it in the original pointing center (since it is -hardcoded- to always be DELAY_DIR when you want to write out a beam corrected ms). So it should not be hardcoded, but have an option where the user can specify an arbitrary direction (BBS had the functionally to do this). Very logical would be that if the user does not specify something it takes out the beam in the current PHASE_DIR (so again this conflicts with the hardcoded DELAY_DIR choice). For a non-phase shifted dataset this means it will be identical to the DELAY_DIR (or REF_DIR since I think in practice I have never seen the REF_DIR to be different from the DELAY_DIR, although I guess it theory it could happen). In principle REF_DIR "cleaner" than  DELAY_DIR since REF_DIR refers to what the station beam former did (DELAY_DIR is just a correlator related setting).

**Comment by aroffringa** [comment]
Ok, that isn't hard to implement, I'll do that soon. I've implemented #60 first, since otherwise the applied beam would be different for new and old DPPPs, without having a way to know. With these keywords, it's also possible for wsclean to automatically determine the right (the use differential beam etc keyword would no longer be necessary, and wsclean will understand what the direction that is applied irrespective of where it was applied).

**Comment by aroffringa** [comment]
Hi @rvweeren, I've made the following changes in d5614ab (#80):
- Applybeam now has a keyword called 'direction' which let you manually set the direction to which the beam is applied
- If direction is empty, the default is now to use the phase centre instead of the delay direction.
- The applied direction is registered with column keywords (#60), and if you're trying to reapply the beam to a column to which the beam is already applied you get an error.

At this point, WSClean will still use the `REFERENCE_DIR`, so there's a nice opportunity to corrupt images by combining new DP3 with phase shifts or manual direction with old `wsclean` ;), but I'll implement soon in WSClean/IDG to use the keywords. Once also implemented in WSClean, it will mean that the differential beam option doesn't need to be specified, as it will get that from the keywords.

This solves this issue, correct?

**Comment by aroffringa** [comment]
The trunk version of WSClean now also honours the keywords.

**Comment by rvweeren** [comment]
Correct, I think this addresses it (it is a nice improvement, this should save time in the future and prevents mistakes/confusion)
