### ISSUE TITLE
Predict/ThreadPool problem: std exception detected: vector::reserve

### ISSUE THREAD

**Issue by darafferty** [lofar-astron/DP3#73]
At the start of a GainCal step (from Prefactor), I get the error "std exception detected: vector::reserve". gdb gives the following info:

```
Processing 1798 time slots ...

0%[New Thread 0x15553c4da700 (LWP 31675)]
[New Thread 0x15553c2d9700 (LWP 31676)]
[New Thread 0x15553c0d8700 (LWP 31677)]
[New Thread 0x15553bed7700 (LWP 31678)]
[New Thread 0x15553bcd6700 (LWP 31679)]
[New Thread 0x15553bad5700 (LWP 31680)]

Thread 1 "DPPP" hit Catchpoint 1 (exception thrown), 0x000015554f3af8bd in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
(gdb) bt
#0  0x000015554f3af8bd in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x000015554f3d826f in std::__throw_length_error(char const*) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x00000000004deba8 in std::vector<std::thread, std::allocator<std::thread> >::reserve(unsigned long) ()
#3  0x00000000005864d8 in DP3::ThreadPool::ThreadPool(unsigned long) ()
#4  0x00000000005846ea in DP3::DPPP::Predict::process(DP3::DPPP::DPBuffer const&) ()
#5  0x000000000055b3a6 in DP3::DPPP::GainCal::process(DP3::DPPP::DPBuffer const&) ()
#6  0x0000000000512e92 in DP3::DPPP::Filter::process(DP3::DPPP::DPBuffer const&) ()
#7  0x000000000049b369 in DP3::DPPP::MSReader::process(DP3::DPPP::DPBuffer const&) ()
#8  0x000000000045782f in DP3::DPPP::DPRun::execute(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, char**) ()
#9  0x0000000000454c1e in main ()
```
The command I used was:

`
DPPP gaincal.usebeammodel=True gaincal.parmdb=instrument_directionindependent msin.baseline="CS*&; RS*&; CS*&RS*" gaincal.caltype=phaseonly gaincal.usechannelfreq=True gaincal.type=gaincal gaincal.solint=1 gaincal.nchan=0 msin.datacolumn=DATA gaincal.sourcedb=/beegfs/stuf316/2A0335ours/prefactor/Pre-Facet-Target2/2A0335ours_field.make_sourcedb_target steps="[filter,gaincal]" msout=L658738_SB001_uv_12C377384t_164MHz.msdpppconcat gaincal.beammode=array_factor msout.datacolumn=CORRECTED_DATA gaincal.maxiter=500 numthreads=2 msin=L658738_SB001_uv_12C377384t_164MHz.msdpppconcat
`

Let me know if you need more info or the data...

**Comment by aroffringa** [comment]
Thanks -- it looks like another forgotten propagation of nthreads (it really would have been easier implementing that by integrating it in the msinfo, as @tammojan also mentioned in the commit review), but I haven't tested whether this fixes it... Could you give branch vector-reserve-exception-#73 (e51cc66) a try?

**Comment by darafferty** [comment]
Thanks, that seems to have fixed the error above, but now I get one related to casacore:

```
Processing 1798 time slots ...

0%[New Thread 0x15553c4da700 (LWP 11288)]
[New Thread 0x15553c2d9700 (LWP 11289)]
[New Thread 0x15553c0d8700 (LWP 11290)]
[New Thread 0x15553bed7700 (LWP 11291)]
[New Thread 0x15553bcd6700 (LWP 11292)]
[New Thread 0x15553bad5700 (LWP 11293)]

Thread 1 "DPPP" received signal SIGSEGV, Segmentation fault.
0x0000155553bbbdfb in casa::MeasFrame::resetEpoch(casa::Measure const&) () from /home/lofar/opt4/casacore/lib/libcasa_measures.so.2
(gdb) bt
#0  0x0000155553bbbdfb in casa::MeasFrame::resetEpoch(casa::Measure const&) () from /home/lofar/opt4/casacore/lib/libcasa_measures.so.2
#1  0x0000000000584595 in DP3::DPPP::Predict::process(DP3::DPPP::DPBuffer const&) ()
#2  0x000000000055b3dc in DP3::DPPP::GainCal::process(DP3::DPPP::DPBuffer const&) ()
#3  0x0000000000512e92 in DP3::DPPP::Filter::process(DP3::DPPP::DPBuffer const&) ()
#4  0x000000000049b369 in DP3::DPPP::MSReader::process(DP3::DPPP::DPBuffer const&) ()
#5  0x000000000045782f in DP3::DPPP::DPRun::execute(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, char**) ()
#6  0x0000000000454c1e in main ()

```

**Comment by aroffringa** [comment]
I ran your command on one of my mses/models and got an exception too, but it is different than yours. Yours looks a bit more scary, possibly having to do with calling casacore from multiple threads... But maybe now mine is fixed, yours could be fixed too. Could you check it? (in the same branch, commit 9b8cc6f1903674b44df46e56b9d4f20cf2f2a9c2 ).

**Comment by darafferty** [comment]
Yep, the last fix seems to have worked -- thanks!

**Comment by aroffringa** [comment]
Great (pfew!), thanks! I'll submit a pull request.
