### ISSUE TITLE
Minimum number of visibilities in solve

### ISSUE THREAD

**Issue by revoltek** [lofar-astron/DP3#83]
In certain cases there are several stations flagged and the solver tries anyway to find solutions, obtaining noisy results. Can you add a "minimum number of baselines" option that if not satisfied flag the solution? Alternatively the same result can be achieved with a flagger step. Not sure what is the best approach.

**Comment by aroffringa** [comment]
Just to be sure: This is for the DDECal task, is that right @revoltek ?

**Comment by aroffringa** [comment]
@revoltek : I've implemented a feature to skip calibration of intervals with fewer unflagged visibilities. You can set it with the parset keyword ddecal.minvisratio=... , e.g. minvisratio=0.6 would require 60% unflagged visibilities in a set. I've done a quick test and it seems to work, but I don't have a good set with your problematic cases, so it would be good if you test it. It is committed to the branch named `min-visibilities-for-solve`.

**Comment by revoltek** [comment]
Thanks for implementing this. Best is to have this in both solvers as the situation of having a few flagged data points can happen any time (e.g. I usually flag data below a certain elevation, on the elevation transition this create a few time slots where some antennas meet the elevation requirement while others don't, this fix should solve the problems by flagging those data points automatically). The default values is  0 I suppose. I will test it today!

**Comment by aroffringa** [comment]
The non-DDECal does already have a `minblperant`. That's not enough for what you want, is it?

If the DDE option has been tested I'll try to implement the non-DDE.

**Comment by revoltek** [comment]
I think your implementation of a minvisratio is a better parameter, more general, than the minblperant. Anyway, this is a secondary problem (I will keep using minblperant for now) but we might leave the ticket open to remeber to put it into DIE solver as well

**Comment by revoltek** [comment]
@tammojan is the minblperant implemented in the DIE solver? I get a:
*** WARNING: the following parset keywords were not used ***
             maybe they are misspelled
    [sol.minblperant]

with parset:
msin =
msin.datacolumn = SMOOTHED_DATA
msout = .
msout.datacolumn = CORRECTED_DATA
numthreads = 0 # the pipeline will set this number
steps = [sol]
sol.type = gaincal
sol.uvlambdamin=300
sol.caltype = diagonal
sol.maxiter = 500
sol.tolerance = 1e-2
sol.nchan = 1
sol.solint = 1
sol.propagatesolutions = False #TBD
sol.usemodelcolumn = True
sol.minblperant = 10

**Comment by revoltek** [comment]
The SB I gave as an example in #100 has >60% of data flagged and I am expecting a large number of solutions flagged (nans), but using a 0.9 as minvis I get 26/210844 set to nan. Using 0.99 I get the same number.

**Comment by revoltek** [comment]
Actually even con minvis=1 I cannot find flags... (I am using the last update, I see the log:
  min visib. ratio:    1

**Comment by revoltek** [comment]
One other thing that I notice is a possible problem with the uvlambdamin which in certain cases reach the threshold of the minvisratio and flags the solution because of that cut. This might not be very easy to solve...

**Comment by revoltek** [comment]
It looks like on the other hand that the sol.uvlambdamin has an effect combined with minvisratio (as expected, i.e. long wavelengths are flagged because >60% of the baselines fall below the uvlambdamin cut, I also see a time dependency due to projection of baselines - so that looks correct)
