### ISSUE TITLE
BLAS : Program is Terminated. Because you tried to allocate too many memory regions.

### ISSUE THREAD

**Issue by revoltek** [lofar-astron/DP3#94]
In our new cluster (AMD powered, not sure if relevant) I find this:

MSReader
  input MS:       /localwork/fdg/zwcl0634/nodysco/tgts/mss/TC00.MS
  band            0
  startchan:      0  (0)
  nchan:          488  (0)
  ncorrelations:  4
  nbaselines:     703
  ntimes:         899
  time interval:  4.00556
  DATA column:    SMOOTHED_DATA
  WEIGHT column:  WEIGHT_SPECTRUM
  autoweight:     false
DDECal ddecal.
  H5Parm:              mss/TC00.MS/tec.h5
  solint:              3
  nchan:               1
  directions:          [[]]
  use model column:    true
  tolerance:           0.0005
  max iter:            500
  propagatesolutions:  true
  detect stalling:     true
  step size:           0.2
  mode (constraints):  tec
  coreconstraint:      0
  smoothnessconstraint:0
  approximate fitter:  true
  subtract model:      false
UVWFlagger ddecal.
  uvm:            []
  um:             []
  vm:             []
  wm:             []
  uvlambda:       [-1e+15,250]
  ulambda:        []
  vlambda:        []
  wlambda:        []
  phasecenter:    []
MSUpdater msout.
  MS:             /localwork/fdg/zwcl0634/nodysco/tgts/mss/TC00.MS
  datacolumn:     CORRECTED_DATA  (has been added to the MS)
  weightcolumn    WEIGHT_SPECTRUM
  writing:        data
  Compressed:     no

  flush:          0

Processing 899 time slots ...

0%BLAS : Program is Terminated. Because you tried to allocate too many memory regions.

however the node has 256 GB of memory and I am using the same command I tried an similar (or even less powerful) systems.

**Comment by aroffringa** [comment]
I suspect this has to do with your BLAS installation on your cluster. I can't help you with that...

**Comment by aroffringa** [comment]
Check your blas help, there's a FAQ on this item: https://github.com/xianyi/OpenBLAS/wiki/faq#allocmorebuffers

**Comment by revoltek** [comment]
ok, thanks :)
