### ISSUE TITLE
additional direction table in DDEcal for h5parms 

### ISSUE THREAD

**Issue by adrabent** [lofar-astron/DP3#97]
Hi,

I encountered some kind of "inconsistency" in DPPP when handling h5parm in `DDEcal`.
If I use DDEcal in the mode `rotation+diagonal` I just get a solution table, like `phase000` with 120 times, 60 ants, 1484 freqs, 2 pol.
But If I just change to the mode `diagonal` in `DDEcal` I get a solution table, like `phase000` with 120 times, 60ants , 1484, 1 dir, 2 pol. Where does this direction table come from and is it really needed if solving only for one direction. And why does it not appear if one solves for common rotation angle?

Alex

**Comment by aroffringa** [comment]
There are indeed a few issues with the solution formatting (and their weights). From what you describe that sounds really like a inconsistency, which is probably in the H5parm code. I'm not really familiar with the H5parm stuff (and don't have time to work on that), that was all @tammojan 's work, but he's not working on DP3. So I'm afraid this remains an issue until ASTRON assigns a new developer.

**Comment by adrabent** [comment]
I tested different solvers and basically any solver I have used creates a `dir` table, except of `rotation` and `rotation+diagonal`. Thus, I tried to dig into the code a bit. I don't have the impression this is an h5parm issue. Could it be that for those two solve modes the constraints overwrite the axes?

https://github.com/lofar-astron/DP3/blob/master/DDECal/RotationAndDiagonalConstraint.cc
(see line 21 or 29)

**Comment by aroffringa** [comment]
I've changed this a bit and it might solve the issue; could you test the hdf5-rotation-direction-table branch? ( d4912528c4d58198b53c771f3f5e4f4b88bbe225 )

**Comment by adrabent** [comment]
Dear @aroffringa,
same issues arises now when using `mode = phaseonly`. Maybe we should re-open that issue.

Alex

**Comment by aroffringa** [comment]
> Dear @aroffringa, same issues arises now when using `mode = phaseonly`. Maybe we should re-open that issue.
> 
> Alex

To record the conclusion here: If I understand it correctly, this turned to be not an issue in Dp3, but rather be a bug in LINC.
